#!/bin/bash

DIR=`dirname $0`

type rg >& /dev/null
RC=$?; if [ "$RC" == "0" ]; then
  echo -e "INIT\t: ripgrep installed"
else
  curl -LO https://github.com/BurntSushi/ripgrep/releases/download/11.0.2/ripgrep_11.0.2_amd64.deb
  sudo dpkg -i ripgrep_11.0.2_amd64.deb
fi

rm -rf api/Seeker*
$DIR/js/build.js

cp node_modules/scv-bilara/src/tipitaka.js src
cp node_modules/scv-bilara/src/sutta-central-id.js src
cp node_modules/scv-bilara/src/suidmap.js src

git status | grep 'nothing to commit' ; RC=$?
if [ "$RC" == "0" ]; then
  echo -e "BUILD\t:nothing to commit"
else
  echo -e "BUILD\t:committing build changes"
  git add api
  git commit -am "build examples"
  git push
fi

