#!/usr/bin/env node

const http = require('http');
const express = require('express');
const app = module.exports = express();

app.use('/test', express.static('dist'))


const PORT = 3000;
app.listen(PORT, ()=>{
    console.log(`listening on http://localhost:${PORT}/test`);
});

