#!/bin/bash

DIR=`dirname $0`

type rg >& /dev/null
RC=$?; if [ "$RC" == "0" ]; then
  echo -e "INIT\t: ripgrep installed"
else
  curl -LO https://github.com/BurntSushi/ripgrep/releases/download/11.0.2/ripgrep_11.0.2_amd64.deb
  sudo dpkg -i ripgrep_11.0.2_amd64.deb
fi

rg --version
