#!/bin/bash

GROUP=$1
if [ "$GROUP" == "" ]; then
  echo -e "WIKI\t: expected group name (ERROR)"
  exit -1
fi

echo -e "WIKI\t: creating $SLUGFILE"
mkdir -p pages/$GROUP
SLUGFILE=pages/$GROUP/_slug.vue 
cat > $SLUGFILE << SLUG
<template>
  <scv-article :article="article">
    <nuxt-content :document="article" />
  </scv-article>
</template>
<script>
  import ScvArticle from '@/components/scv-article';
  export default {
    async asyncData({ \$content, params }) {
      const article = await \$content('$GROUP', params.slug).fetch()
      return { article }
    },
    components: { ScvArticle, },
  }
</script>
SLUG

echo -e "WIKI\t: creating content/$GROUP"
if [ ! -e "content/wiki/$GROUP.md" ]; then
  echo -e "WIKI\t: creating content/wiki/$GROUP.md"
cat > content/wiki/$GROUP.md << MDGROUP
---
title: $GROUP title
description: $GROUP description
img: candle.png
img-alt: Generic image for $GROUP 
slugDir: $GROUP
order: 9999
---
### Welcome to $GROUP!
This is the main
page for the wiki group "$GROUP".

To change this file, edit <code>content/wiki/$GROUP.md</code>.
This file is a [Markdown](https://www.markdownguide.org/basic-syntax) file.

### Wiki/$GROUP Contents
The pages in your new group are shown below.
We've created an Example page for you.

MDGROUP
fi # GROUP.md

echo -e "WIKI\t: creating content/$GROUP/example.md"
mkdir -p content/$GROUP
cat > content/$GROUP/example.md << MDEXAMPLE
---
title: Example page for wiki/$GROUP 
description: Example description
img: amanda-flavell-9XSLoMlVhYU-unsplash.png
img-alt: Generic image for $GROUP example
---
### Copy this page
This wiki page is stored in <code>content/$GROUP/example.md</code>.

To make a new page in <code>content/$GROUP</code>,
simply copy this page 
to a new file (e.g., "my-new-page.md"):
<code>content/$GROUP/my-new-page.md</code>

Edit your new page as you see fit. 
Start by changing the YAML block at the top of your copied file:

\`\`\`
title: Example title
description: Example description
img: The file name or URL of an optional image
img-alt: The accessibility label for the image
order: The display order of this page in the group. Pages with the same number are sorted alphabetically
\`\`\`

Everything below the YAML header is 
[Markdown](https://www.markdownguide.org/basic-syntax).
MDEXAMPLE
