name: push-actions
on: [push]
jobs:
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
      - run: npm install
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: npm run deploy
